<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Test basic_SUITE:test2 result</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<a name="top"></a><pre>
=== Test case: <a href="basic_suite.src.html#test2-1">basic_SUITE:test2/1</a> (click for source code)

=== Config value:

    [{watchdog,&lt;0.142.0&gt;},
     {tc_logfile,"/home/pbove/git/erlang-for-great-good/chapter28/ct/demo/ct_run.ct@pbove.2021-03-09_15.00.00/ct.demo.basic_SUITE.logs/run.2021-03-09_15.00.01/basic_suite.test2.html"},
     {tc_group_properties,[{suite,basic_SUITE}]},
     {tc_group_path,[]},
     {data_dir,"/home/pbove/git/erlang-for-great-good/chapter28/ct/demo/basic_SUITE_data/"},
     {priv_dir,"/home/pbove/git/erlang-for-great-good/chapter28/ct/demo/ct_run.ct@pbove.2021-03-09_15.00.00/ct.demo.basic_SUITE.logs/run.2021-03-09_15.00.01/log_private/"}]

=== Current directory is "/home/pbove/git/erlang-for-great-good/chapter28/ct/demo/ct_run.ct@pbove.2021-03-09_15.00.00"

=== Started at 2021-03-09 15:00:01

<br />

</pre>
<div class="ct_error_notify"><pre><b>*** CT Error Notification 2021-03-09 15:00:01.373 ***</b>
basic_SUITE:test2 failed on line 13
Reason: {badarith,[{basic_SUITE,...},{...}|...]}

<a href="#end">Full error description and stacktrace</a>
</pre></div>
<pre>
<a name="end"></a>


=== Ended at 2021-03-09 15:00:01
=== Location: [{basic_SUITE,test2,<a href="basic_suite.src.html#13">13</a>},
              {test_server,ts_tc,1754},
              {test_server,run_test_case_eval1,1263},
              {test_server,run_test_case_eval,1195}]
=== === Reason: an error occurred when evaluating an arithmetic expression
  in function  basic_SUITE:test2/1 (basic_SUITE.erl, line 13)
  in call from test_server:ts_tc/3 (test_server.erl, line 1754)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1263)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1195)
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2021 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Tue Mar 09 2021 15:00:01<!--/date--><br />
</div>
</center>
</body>
</html>
